# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/NextStateProductor.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/Dtrigger.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/SignZeroExtend.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/RegisterFile.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/PCPlus4.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/PC.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/Multiplexer4_32.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/Multiplexer2_32_5.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/Multiplexer2_32.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/J_Address.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/IR.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/InstructMemory.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/DataSync.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/DataMemory.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/ControlUnit.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/BranchPlus.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/ALU.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/Show.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/KeyDown.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/DIVCLK.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/Display.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/CPU.v
  H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/sources_1/imports/new/top.v
}
read_xdc H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/constrs_1/imports/new/topcons.xdc
set_property used_in_implementation false [get_files H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.srcs/constrs_1/imports/new/topcons.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Vivado/VivadoProject/MultiCPUBasys3/MultiCPUBasys3.cache/wt [current_project]
set_property parent.project_dir H:/Vivado/VivadoProject/MultiCPUBasys3 [current_project]
catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7a35tcpg236-1
write_checkpoint top.dcp
report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb
