# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/SignZeroExtend.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/RegisterFile.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/PCPlus4.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/PC.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/Multiplexer4_32.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/Multiplexer2_5.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/Multiplexer2_32_5.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/Multiplexer2_32.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/J_Address.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/InstructMemory.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/DataMemory.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/ControlUnit.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/BranchPlus.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/ALU.v
  H:/Vivado/VivadoProject/SingleCPU/SingleCPU.srcs/sources_1/new/CPU.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Vivado/VivadoProject/SingleCPU/SingleCPU.cache/wt [current_project]
set_property parent.project_dir H:/Vivado/VivadoProject/SingleCPU [current_project]
catch { write_hwdef -file CPU.hwdef }
synth_design -top CPU -part xc7a35tcpg236-1
write_checkpoint CPU.dcp
report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb
